### ISSUE TITLE
CDN links

### ISSUE THREAD

**Issue by epexa** [lino-network/lino-js#49]
**add CDN links in the [README.md](https://github.com/lino-network/lino-js/blob/1a2ef077da91b0f51df86cc616b51dc5bd5802d2/readme.md).**

last version:
https://cdn.jsdelivr.net/npm/lino-js/lib/lino-js.umd.min.js

or specific version:
https://cdn.jsdelivr.net/npm/lino-js@1.0.2/lib/lino-js.umd.min.js

_if it is needed, i will make a pull request where i will document them._

**Comment by epexa** [comment]
@xiaoxiaff done!

**Comment by xiaoxiaff** [comment]
Thx for the PR :)
