### ISSUE TITLE
getRelationship is not a function

### ISSUE THREAD

**Issue by Crowbrammer** [lino-network/lino-js#53]
In the documentation in README.md#get-donation-relationship there is a method getRelationship:

```js
lino.query
    .getRelationship(me, other)
    .then(v => {
        console.log('getRelationship: ', v);
    }); 
```

Screenshot:
![image](https://user-images.githubusercontent.com/19522656/60853974-61ef8c00-a1cc-11e9-82fb-560c9a83a7dc.png)

Lino setup:
```js
lino = new LINO({
  nodeUrl: "https://fullnode.lino.network/",
  chainId: "lino-testnet-upgrade1"
});
```
lino-js version: 1.0.19

**Comment by xiaoxiaff** [comment]
Hi @Crowbrammer, this function is deprecated and removed. I will update the doc and code. Thx! :)
